---
- name: Master initialisieren
  command:
    cmd: "kubeadm init --pod-network-cidr=192.168.0.0/16"
    creates: /etc/kubernetes/manifests/kube-apiserver.yaml

- name: Flannel Network-Definition einspielen
  get_url:
    url: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    dest: /root/kube-flannel.yml    

- name: POD-Netzwerk initialisieren
  shell:
    cmd: "KUBECONFIG=/etc/kubernetes/admin.conf kubectl apply -f kube-flannel.yml"

- name: join-command isolieren
  command:
    cmd: "kubeadm token create --print-join-command"
  register: join_command

- name: join-command ablegen
  copy:
    content: "{{ join_command.stdout }}"
    dest: join-command
  delegate_to: localhost

- name: config für kubectl runterziehen
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: config
    flat: yes
